# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Serial_control_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Anticlockwise_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Anticlockwise_pushButton.setEnabled(True)
        self.Anticlockwise_pushButton.setGeometry(QtCore.QRect(30, 150, 91, 31))
        self.Anticlockwise_pushButton.setMouseTracking(False)
        self.Anticlockwise_pushButton.setTabletTracking(False)
        self.Anticlockwise_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Anticlockwise_pushButton.setAutoFillBackground(False)
        self.Anticlockwise_pushButton.setCheckable(False)
        self.Anticlockwise_pushButton.setAutoRepeat(False)
        self.Anticlockwise_pushButton.setAutoDefault(False)
        self.Anticlockwise_pushButton.setObjectName("Anticlockwise_pushButton")
        self.Off_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Off_pushButton.setGeometry(QtCore.QRect(150, 150, 91, 31))
        self.Off_pushButton.setObjectName("Off_pushButton")
        self.Cloclwise_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Cloclwise_pushButton.setGeometry(QtCore.QRect(270, 150, 91, 31))
        self.Cloclwise_pushButton.setObjectName("Cloclwise_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Anticlockwise_pushButton.setText(_translate("MainWindow", "Anti-Clockwise"))
        self.Off_pushButton.setText(_translate("MainWindow", "Off"))
        self.Cloclwise_pushButton.setText(_translate("MainWindow", "Clockwise"))

